ServerName wacdo-web

LoadModule deflate_module modules/mod_deflate.so

ServerTokens Prod
ServerSignature Off

<Directory />
    AllowOverride None
    Require all denied
</Directory>

LogLevel warn
ErrorLog /proc/self/fd/2
CustomLog /proc/self/fd/1 combined
